/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InfoCollectionForm;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TGDD
 */
public class InfoCollectionJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoCollectionJFrame
     */
    public InfoCollectionJFrame() {
        initComponents();
        notifyLabel09.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroupBtn09 = new javax.swing.ButtonGroup();
        background09 = new javax.swing.JPanel();
        formTitle09 = new javax.swing.JLabel();
        nameLabel09 = new javax.swing.JLabel();
        nameTF09 = new javax.swing.JTextField();
        genderLabel09 = new javax.swing.JLabel();
        maleRadioBtn09 = new javax.swing.JCheckBox();
        femaleRadioBtn09 = new javax.swing.JCheckBox();
        otherRadioBtn09 = new javax.swing.JCheckBox();
        dobLabel09 = new javax.swing.JLabel();
        dayCBox09 = new javax.swing.JComboBox<>();
        monthCBox09 = new javax.swing.JComboBox<>();
        yearCBox09 = new javax.swing.JComboBox<>();
        jobLabel09 = new javax.swing.JLabel();
        JobTF09 = new javax.swing.JTextField();
        phoneNumLabel09 = new javax.swing.JLabel();
        phoneNumTF09 = new javax.swing.JTextField();
        emailTF09 = new javax.swing.JTextField();
        emailLabel09 = new javax.swing.JLabel();
        addressTF09 = new javax.swing.JTextField();
        addressLabel09 = new javax.swing.JLabel();
        saveBtn09 = new javax.swing.JButton();
        notifyLabel09 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextarea09 = new javax.swing.JTextArea();
        resetBtn09 = new javax.swing.JButton();
        iconGuessLabel09 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông tin người tham dự");

        background09.setBackground(new java.awt.Color(255, 255, 255));

        formTitle09.setBackground(new java.awt.Color(204, 255, 255));
        formTitle09.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        formTitle09.setForeground(new java.awt.Color(255, 153, 51));
        formTitle09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle09.setIcon(new javax.swing.ImageIcon("D:\\Code_Java\\INFORMATIONCOLLECTIONFORM\\Img\\icons8-info-36.png")); // NOI18N
        formTitle09.setText(" THÔNG TIN NGƯỜI THAM DỰ");
        formTitle09.setOpaque(true);

        nameLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        nameLabel09.setText(" Họ tên người tham dự *");

        nameTF09.setBackground(new java.awt.Color(204, 255, 255));
        nameTF09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTF09ActionPerformed(evt);
            }
        });

        genderLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        genderLabel09.setText(" Giới tính *");

        maleRadioBtn09.setBackground(new java.awt.Color(204, 255, 255));
        genderGroupBtn09.add(maleRadioBtn09);
        maleRadioBtn09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maleRadioBtn09.setSelected(true);
        maleRadioBtn09.setText("  Nam");
        maleRadioBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtn09ActionPerformed(evt);
            }
        });

        femaleRadioBtn09.setBackground(new java.awt.Color(204, 255, 255));
        genderGroupBtn09.add(femaleRadioBtn09);
        femaleRadioBtn09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        femaleRadioBtn09.setText("Nữ");
        femaleRadioBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtn09ActionPerformed(evt);
            }
        });

        otherRadioBtn09.setBackground(new java.awt.Color(204, 255, 255));
        genderGroupBtn09.add(otherRadioBtn09);
        otherRadioBtn09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        otherRadioBtn09.setText("Khác");
        otherRadioBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRadioBtn09ActionPerformed(evt);
            }
        });

        dobLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        dobLabel09.setText(" Ngày sinh *");

        dayCBox09.setBackground(new java.awt.Color(204, 255, 255));
        dayCBox09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        monthCBox09.setBackground(new java.awt.Color(204, 255, 255));
        monthCBox09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12", " " }));

        yearCBox09.setBackground(new java.awt.Color(204, 255, 255));
        yearCBox09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        yearCBox09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearCBox09ActionPerformed(evt);
            }
        });

        jobLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jobLabel09.setText(" Nghề nghiệp");

        JobTF09.setBackground(new java.awt.Color(204, 255, 255));
        JobTF09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JobTF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobTF09ActionPerformed(evt);
            }
        });

        phoneNumLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        phoneNumLabel09.setText(" Số điện thoại *");

        phoneNumTF09.setBackground(new java.awt.Color(204, 255, 255));
        phoneNumTF09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneNumTF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTF09ActionPerformed(evt);
            }
        });

        emailTF09.setBackground(new java.awt.Color(204, 255, 255));
        emailTF09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailTF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTF09ActionPerformed(evt);
            }
        });

        emailLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        emailLabel09.setText(" Email");

        addressTF09.setBackground(new java.awt.Color(204, 255, 255));
        addressTF09.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTF09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTF09ActionPerformed(evt);
            }
        });

        addressLabel09.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        addressLabel09.setText(" Địa chỉ *");

        saveBtn09.setBackground(new java.awt.Color(255, 153, 153));
        saveBtn09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn09.setIcon(new javax.swing.ImageIcon("D:\\Code_Java\\INFORMATIONCOLLECTIONFORM\\Img\\icons8-save-28.png")); // NOI18N
        saveBtn09.setText("Lưu");
        saveBtn09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveBtn09MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveBtn09MouseReleased(evt);
            }
        });
        saveBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn09ActionPerformed(evt);
            }
        });

        notifyLabel09.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifyLabel09.setText("Lưu thành công ...");

        infoTextarea09.setColumns(20);
        infoTextarea09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        infoTextarea09.setRows(5);
        infoTextarea09.setToolTipText("");
        infoTextarea09.setAutoscrolls(false);
        infoTextarea09.setEnabled(false);
        jScrollPane1.setViewportView(infoTextarea09);

        resetBtn09.setBackground(new java.awt.Color(51, 255, 51));
        resetBtn09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetBtn09.setForeground(new java.awt.Color(51, 51, 255));
        resetBtn09.setIcon(new javax.swing.ImageIcon("D:\\Code_Java\\INFORMATIONCOLLECTIONFORM\\Img\\icons8-reset-24.png")); // NOI18N
        resetBtn09.setText("Làm mới");
        resetBtn09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetBtn09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetBtn09MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetBtn09MouseReleased(evt);
            }
        });
        resetBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtn09ActionPerformed(evt);
            }
        });

        iconGuessLabel09.setForeground(new java.awt.Color(0, 0, 255));
        iconGuessLabel09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconGuessLabel09.setIcon(new javax.swing.ImageIcon("D:\\Code_Java\\INFORMATIONCOLLECTIONFORM\\Img\\icons8-user-64.png")); // NOI18N
        iconGuessLabel09.setEnabled(false);

        javax.swing.GroupLayout background09Layout = new javax.swing.GroupLayout(background09);
        background09.setLayout(background09Layout);
        background09Layout.setHorizontalGroup(
            background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background09Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background09Layout.createSequentialGroup()
                        .addComponent(formTitle09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(background09Layout.createSequentialGroup()
                        .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumTF09)
                            .addComponent(JobTF09)
                            .addComponent(dobLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(background09Layout.createSequentialGroup()
                                .addComponent(maleRadioBtn09)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioBtn09, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(otherRadioBtn09))
                            .addComponent(nameTF09)
                            .addComponent(nameLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(background09Layout.createSequentialGroup()
                                .addComponent(dayCBox09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthCBox09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearCBox09, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jobLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumLabel09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTF09)
                            .addComponent(addressLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressTF09)
                            .addComponent(notifyLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveBtn09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background09Layout.createSequentialGroup()
                                .addComponent(resetBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background09Layout.createSequentialGroup()
                                .addComponent(iconGuessLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background09Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        background09Layout.setVerticalGroup(
            background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background09Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle09)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconGuessLabel09, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addGroup(background09Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nameLabel09)
                        .addGap(1, 1, 1)
                        .addComponent(nameTF09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(background09Layout.createSequentialGroup()
                        .addComponent(genderLabel09)
                        .addGap(1, 1, 1)
                        .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadioBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleRadioBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otherRadioBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dobLabel09)
                        .addGap(1, 1, 1)
                        .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayCBox09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthCBox09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearCBox09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jobLabel09)
                        .addGap(1, 1, 1)
                        .addComponent(JobTF09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumLabel09)
                        .addGap(1, 1, 1)
                        .addComponent(phoneNumTF09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailLabel09)
                        .addGap(1, 1, 1)
                        .addComponent(emailTF09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressLabel09)
                        .addGap(1, 1, 1)
                        .addComponent(addressTF09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(notifyLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTF09ActionPerformed

    private void maleRadioBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtn09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioBtn09ActionPerformed

    private void femaleRadioBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtn09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioBtn09ActionPerformed

    private void otherRadioBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRadioBtn09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherRadioBtn09ActionPerformed

    private void JobTF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobTF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobTF09ActionPerformed

    private void yearCBox09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearCBox09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearCBox09ActionPerformed

    private void phoneNumTF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumTF09ActionPerformed

    private void emailTF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTF09ActionPerformed

    private void addressTF09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTF09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTF09ActionPerformed

    private void resetBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtn09ActionPerformed
        // TODO add your handling code here:
        nameTF09.setText("");
        maleRadioBtn09.setSelected(true);
        JobTF09.setText("");
        phoneNumTF09.setText("");
        emailTF09.setText("");
        addressTF09.setText("");
        infoTextarea09.setText("");
        notifyLabel09.setVisible(false);

    }//GEN-LAST:event_resetBtn09ActionPerformed

    private void saveBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn09ActionPerformed
        // TODO add your handling code here:
        String name = "";
        String gender = "";
        String dob = "";
        String job = "";
        String phoneNum = "";
        String email = "";
        String address = "";
        if (nameTF09.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập họ tên!");
            nameTF09.requestFocus();
            return;
        }
        if(!maleRadioBtn09.isSelected() && !femaleRadioBtn09.isSelected() && !otherRadioBtn09.isSelected()) {
            JOptionPane.showMessageDialog(this, "Cần chọn giới tính!");
            return;
        }
        if((monthCBox09.getSelectedItem() == "Tháng 2" &&
            (dayCBox09.getSelectedItem() == "30" || dayCBox09.getSelectedItem() == "31"))
        || ((monthCBox09.getSelectedItem() == "Tháng 4" || monthCBox09.getSelectedItem() == "Tháng 6" ||
            monthCBox09.getSelectedItem() == "Tháng 9" || monthCBox09.getSelectedItem() == "Tháng 11")
        &&
        (dayCBox09.getSelectedItem() == "31"))
        ) {
            JOptionPane.showMessageDialog(this, "Ngày sinh chưa hợp lệ!");
            return;
        }

        if(phoneNumTF09.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập số điện thoại!");
            phoneNumTF09.requestFocus();
            return;
        }
        if(addressTF09.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập địa chỉ!");
            addressTF09.requestFocus();
            return;
        }

        name = nameTF09.getText();
        if(maleRadioBtn09.isSelected()) {
            gender = "Nam";
        } else if(femaleRadioBtn09.isSelected()) {
            gender = "Nữ";
        } else {
            gender = "Khác";
        }
        dob = dayCBox09.getSelectedItem() + "/" + monthCBox09.getSelectedItem() + "/" + yearCBox09.getSelectedItem();
        job = JobTF09.getText();
        phoneNum = phoneNumTF09.getText();
        email = emailTF09.getText();
        address = addressTF09.getText();

        infoTextarea09.setText("Họ tên: " + name + "\n\n" + "Giới tính: " + gender + "\n\n"
            + "Ngày sinh: " + dob + "\n\n" + "Công việc: " + job + "\n\n" +
            "Số điện thoại: " + phoneNum + "\n\n" + "Email: " + email + "\n\n" + "Địa chỉ: " + address);
        notifyLabel09.setVisible(true);
    }//GEN-LAST:event_saveBtn09ActionPerformed

    private void saveBtn09MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtn09MousePressed
        // TODO add your handling code here:
        saveBtn09.setBackground(Color.green);
        saveBtn09.setForeground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_saveBtn09MousePressed

    private void saveBtn09MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtn09MouseReleased
        // TODO add your handling code here:
        saveBtn09.setBackground(new java.awt.Color(255,153,153));
        saveBtn09.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_saveBtn09MouseReleased

    private void resetBtn09MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtn09MousePressed
        // TODO add your handling code here:
        resetBtn09.setBackground(new java.awt.Color(255,153,153));
        resetBtn09.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_resetBtn09MousePressed

    private void resetBtn09MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtn09MouseReleased
        // TODO add your handling code here:
        resetBtn09.setBackground(new java.awt.Color(51,255,51));
        resetBtn09.setForeground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_resetBtn09MouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCollectionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCollectionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCollectionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCollectionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCollectionJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JobTF09;
    private javax.swing.JLabel addressLabel09;
    private javax.swing.JTextField addressTF09;
    private javax.swing.JPanel background09;
    private javax.swing.JComboBox<String> dayCBox09;
    private javax.swing.JLabel dobLabel09;
    private javax.swing.JLabel emailLabel09;
    private javax.swing.JTextField emailTF09;
    private javax.swing.JCheckBox femaleRadioBtn09;
    private javax.swing.JLabel formTitle09;
    private javax.swing.ButtonGroup genderGroupBtn09;
    private javax.swing.JLabel genderLabel09;
    private javax.swing.JLabel iconGuessLabel09;
    private javax.swing.JTextArea infoTextarea09;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobLabel09;
    private javax.swing.JCheckBox maleRadioBtn09;
    private javax.swing.JComboBox<String> monthCBox09;
    private javax.swing.JLabel nameLabel09;
    private javax.swing.JTextField nameTF09;
    private javax.swing.JLabel notifyLabel09;
    private javax.swing.JCheckBox otherRadioBtn09;
    private javax.swing.JLabel phoneNumLabel09;
    private javax.swing.JTextField phoneNumTF09;
    private javax.swing.JButton resetBtn09;
    private javax.swing.JButton saveBtn09;
    private javax.swing.JComboBox<String> yearCBox09;
    // End of variables declaration//GEN-END:variables
}
